version: '2'
services:
  box:
    image: busybox
    volumes:
      - /box
  web:
    build: .
    command: rackup -p 3000
    ports:
      - "3000:3000"
    volumes_from:
      - box
    volumes:
      - .:/usr/src/app
